name: test_rk2
on:
  push:
  
jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: build bubble_sort
          shell: bash
          run: |
            git submodule update --init
            cd bubble_sort   
            cmake -H. -B_build
            cmake --build _build
          
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: update
        run:  |
          git submodule update --init
          sudo apt install lcov
          sudo apt install g++-7
      - name: test
        shell: bash
        run: |
          mkdir _build && cd _build
          CXX=/usr/bin/g++-7 cmake -DCOVERAGE=1 ..
          cmake --build .
          ./RunTest
          lcov -t "bubble_sort " -o lcov.info -c -d .
          lcov --remove lcov.info '/home/runner/work/RK_2/RK_2/third-party/gtest/*' -o lcov.info
          lcov --remove lcov.info '/usr/include/*' -o lcov.info
          
  CovTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: update
        run:  |
          git submodule update --init
          sudo apt install lcov
          sudo apt install g++-7
      
      - name: test
        shell: bash
        run: |
          mkdir _build && cd _build
          CXX=/usr/bin/g++-7 cmake -DCOVERAGE=1 ..
          cmake --build .
          ./RunTest
          lcov -t "bubble_sort" -o lcov.info -c -d .
          lcov --remove lcov.info '/home/runner/work/RK_2/RK_2/third-party/gtest/*' -o lcov.info ###
          lcov --remove lcov.info '/usr/include/*' -o lcov.info
          
      - name: CovBeg
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          path-to-lcov: ./_build/lcov.info
          coveralls-endpoint: https://coveralls.io
          
      - name: CovFin
        uses: coverallsapp/github-action@master
        with:
         github-token: ${{ secrets.github_token }}
         parallel-finished: true
